version: 2.1

parameters:
  docker_username:
    type: string
  docker_password:
    type: string

jobs:
  build-and-push:
    docker:
      - image: circleci/docker:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Image
          command: |
            docker build -t << parameters.docker_username >>/my-docker-image:latest .
      - run:
          name: Login to Docker Hub
          command: |
            echo "<< parameters.docker_password >>" | docker login -u "<< parameters.docker_username >>" --password-stdin
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker push << parameters.docker_username >>/my-docker-image:latest

workflows:
  version: 2
  build-and-push-workflow:
    jobs:
      - build-and-push:
          # docker_username: << pipeline.parameters.DOCKER_USERNAME >>
          # docker_password: << pipeline.parameters.DOCKER_PASSWORD >>
