version: 2.1

jobs:
  build-and-push:
    docker:
      - image: circleci/docker:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKER_USERNAME/my-docker-image:latest .
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker push $DOCKER_USERNAME/my-docker-image:latest

workflows:
  version: 2
  build-and-push-workflow:
    jobs:
      - build-and-push
